language: python

install:
  - pip install -r requirements.txt
  - pip install pep8
  - pip install nose

python:
  - "2.7"
  - "3.6"

script:
  - python -m "nose"
  - pep8 pynetbox

jobs:
  include:
    - stage: pypi release
      python: 2.7
      script: echo "Deploying to PyPI..."
      deploy:
        - provider: pypi
          distributions: sdist
          server: https://upload.pypi.org/legacy/
          user: $PYPI_USERNAME
          password: $PYPI_PASSWORD
          on:
            branch: master
            tags: true
